// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $list from "./routes/list.tsx";
import * as $post_id_ from "./routes/post/[id].tsx";
import * as $post_create from "./routes/post/create.tsx";
import * as $search from "./routes/search.tsx";
import * as $AddForm from "./islands/AddForm.tsx";
import * as $ListPosts from "./islands/ListPosts.tsx";
import * as $Search from "./islands/Search.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/list.tsx": $list,
    "./routes/post/[id].tsx": $post_id_,
    "./routes/post/create.tsx": $post_create,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/AddForm.tsx": $AddForm,
    "./islands/ListPosts.tsx": $ListPosts,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
